services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' -C -N"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-init:
    image: mcr.microsoft.com/mssql/server:2019-latest
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./initdb.sql:/tmp/initdb.sql
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
    command: >
      /bin/bash -c "
      echo 'Esperando a SQL Server...' &&
      sleep 10 &&
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P $SA_PASSWORD -i /tmp/initdb.sql -C -N &&
      echo 'Base de datos inicializada correctamente'
      "
    restart: "no"

volumes:
  sql_data: